################################################################################
#   Copyright (c) 2019 AT&T Intellectual Property.                             #
#                                                                              #
#   Licensed under the Apache License, Version 2.0 (the "License");            #
#   you may not use this file except in compliance with the License.           #
#   You may obtain a copy of the License at                                    #
#                                                                              #
#       http://www.apache.org/licenses/LICENSE-2.0                             #
#                                                                              #
#   Unless required by applicable law or agreed to in writing, software        #
#   distributed under the License is distributed on an "AS IS" BASIS,          #
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
#   See the License for the specific language governing permissions and        #
#   limitations under the License.                                             #
################################################################################'
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
ricplt:
# This section is reserved for values imported from RIC Platform charts
  dbaasService: "service-ricplt-dbaas-tcp.ricplt.svc.cluster.local"
  metricsdbService: "service-metricsdb.ricplt.svc.cluster.local"
  pltIngressUrl: "ricplt-entry"
  xappIngressUrl: "ricxapp-entry"

  appmgrRMRService: "service-ricplt-appmgr-rmr.ricplt.svc.cluster.local"
  e2mgrRMRService: "service-ricplt-e2mgr-rmr.ricplt.svc.cluster.local"
  e2termRMRService: "service-ricplt-e2term-rmr.ricplt.svc.cluster.local"
  rtmgrRMRService: "service-ricplt-rtmgr-rmr.ricplt.svc.cluster.local"
  a1mediatorRMRService: "service-ricplt-a1mediator-rmr.ricplt.svc.cluster.local"

# Location of the xApp config files injected from the xApp descriptor
appconfig:
    path: /opt/ric/config

# Location of volume based on HostPath of type Directory
storage:
    mountPath: /home/kpm/storage

# Number of replica
replicaCount: 1

# Image pulling policy
image_pull_policy: IfNotPresent

# Environment variables that will be injected
appenv: {}

# Liveness probe definition. If empty, liveness probe will be disabled
livenessProbe: {}

# Readiness probe definition. If empty, readiness probe will be disabled
readinessProbe: {}

# Instance name. If empty, chart name will be used
name: {}

# Full instance name. If empty, full name will be constructed from name
fullname: {}

###############    The following are from the xApp descriptor     ###############
containers:
- image:
    name: o-ran-sc/ric-app-ts
    registry: nexus3.o-ran-sc.org:10002
    tag: 1.2.5
  name: trafficxapp
controls:
  ts_control_api: grpc
  ts_control_ep: service-ricxapp-rc-grpc-server.ricxapp.svc.cluster.local:7777
messaging:
  ports:
  - container: trafficxapp
    description: rmr receive data port for trafficxapp
    name: rmr-data
    policies:
    - 20008
    port: 4560
    rxMessages:
    - TS_QOE_PREDICTION
    - A1_POLICY_REQ
    - TS_ANOMALY_UPDATE
    txMessages:
    - TS_UE_LIST
    - TS_ANOMALY_ACK
  - container: trafficxapp
    description: rmr route port for trafficxapp
    name: rmr-route
    port: 4561
rmr:
  maxSize: 2072
  numWorkers: 1
  policies:
  - 20008
  protPort: tcp:4560
  rxMessages:
  - TS_QOE_PREDICTION
  - A1_POLICY_REQ
  - TS_ANOMALY_UPDATE
  txMessages:
  - TS_UE_LIST
  - TS_ANOMALY_ACK
version: 1.2.5
xapp_name: trafficxapp
